@startuml

Actor User

User -> ":ControladorMouse": mousePressed(event Event)
":ControladorMouse" -> ":ModeloObservable": inicializarModeloDato(vista.posicion)
":ModeloObservable" -> ":ModeloObservable": setChanged()
":ControladorMouse" -> ":ModeloObservable": notifyObservers(vista)
loop todo Observer
        ":ModeloObservable" -> ":VistaModeloDato": update()
end
@enduml
