@startuml

Actor User

User -> ControladorMous: mousePressed(event Event)
ControladorMous -> ModeloObservable: inicializarModeloDato(vista.posicion)
ModeloObservable -> ModeloObservable: setChanged()
ControladorMous -> ModeloObservable: notifyObservers(vista)
loop todo Observer
        ModeloObservable -> VistaModeloDato: update()
end
@enduml
